### ISSUE TITLE
getting 404 on POST repository/git/blobs (outdated github api)

### ISSUE THREAD

**Issue by Juesto** [bluekeyes/patch2pr#70]
is this project up to date? i've tried to create a pr from a patch and i've been unable to because i receive a 404 response from the api
`error: apply failed: path/to/file: create blob failed: POST https://api.github.com/repos/owner/repo/git/blobs: 404 Not Found []`

**Comment by Juesto** [comment]
on a second thought, maybe im misusing this and it needs me to create a fork beforehand?

**Comment by bluekeyes** [comment]
I take it you've figured out what was wrong, but yes, you'll need to use this library/CLI with a repository where your token has write access. It does not automatically create a fork if one is necessary to submit the pull request.

**Comment by Juesto** [comment]
> I take it you've figured out what was wrong, but yes, you'll need to use this library/CLI with a repository where your token has write access. It does not automatically create a fork if one is necessary to submit the pull request.

would be a good idea to implement, there are cases where even at orgs you dont have write access
