### ISSUE TITLE
Draft PRs

### ISSUE THREAD

**Issue by dvizzini** [bluekeyes/patch2pr#72]
First off, this tool is awesome. Thank you to all that created it!

Secondly, I'm curious if it supports the ability to create draft PRs? If not, that's a feature I might (eventually) add.

Thanks!

**Comment by bluekeyes** [comment]
The CLI does not support creating draft PRs, although you can do it if using the library interface from a Go program. It should be straightforward to add a new CLI flag for this if you'd like to try implementing it. Otherwise, I can probably add it sometime in the next few days.

**Comment by dvizzini** [comment]
@bluekeyes Thanks!
