### ISSUE TITLE
Unable to create commits on my forked repository

### ISSUE THREAD

**Issue by arunsathiya** [bluekeyes/patch2pr#83]
patch2pr sounds really handy! I am having some troubles getting started though.

This is the command that I am running:

```
patch2pr -repository replit/pyright-extended -fork -no-pull-request changes.patch
```

My understanding is that:

- It creates a fork of `replit/pyright-extended` on my account `arunsathiya`
- Commits the patch

And without the `-no-pull-request` flag, it submits a PR too, to upstream `replit/pyright-extended`.

But the command's failing with this error:

```
error: commit failed: create tree failed: POST https://api.github.com/repos/arunsathiya/pyright-extended/git/trees: 404 Not Found []

This may be because the repository does not exist or the token you are using
does not have write permission. If submitting a patch to a repository where you
do not have write access, consider using the -fork flag to submit the patch
from a fork.
```

I have tried the following command too, but it fails with the same error after creating the fork:

```
patch2pr -repository replit/pyright-extended -fork-repository arunsathiya/pyright-extended -no-pull-request changes.patch
```

I see the same behavior with the following types of tokens:

- `repo` classic token
- Fine-grained token with `administration` (which is [required for forking](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-administration)), `contents` ([for committing changes](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-contents)) and `pull requests`

**Comment by bluekeyes** [comment]
My understanding is that the 404 response on the Git data endpoints is due to permission issues, but maybe it is caused in other situations as well.

Since the fork exists now, can you try this command, which should eliminate any issues due to creating a fork?

    patch2pr -repository arunsathiya/pyright-extended -no-pull-request changes.patch

Could you also verify that the fine-grained token either works for all repositories or includes the `arunsathiya/pyright-extended` repository? Since you saw the same error with a classic token, I'm guessing this is not the issue, but I'd like to confirm.

It might also help if you can share the patch you are trying to apply, in case the error is caused by the patch contents.

**Comment by arunsathiya** [comment]
>Since the fork exists now, can you try this command, which should eliminate any issues due to creating a fork?
patch2pr -repository arunsathiya/pyright-extended -no-pull-request changes.patch

Same issue, unfortunately, with the `repo` classic token.

>Could you also verify that the fine-grained token either works for all repositories or includes the arunsathiya/pyright-extended repository?

Tested with a new fine-grained `administration` token and it seems to work fine for this repository and all other repositories I have so far. I haven't tried invoking the git endpoints manually with a `contents` token though, because I am not familiar with that endpoint yet.

>It might also help if you can share the patch you are trying to apply, in case the error is caused by the patch contents.

It's a fairly straightforward change, here:

[changes.patch](https://github.com/bluekeyes/patch2pr/files/13944876/changes.patch)

**Comment by bluekeyes** [comment]
Thanks for sharing the patch - I think that's the source of the problem. Please try granting read and write access to "Workflows" with your fine-grained token or adding the `workflow` scope to your classic token.

I've found this is inconsistently documented in GitHub's API docs [^1], but modifying workflow files for GitHub Actions requires additional permissions that are not needed to modify other types of files in the same repository. I believe this is a security measure to reduce the risk of unauthorized changes to workflows, but it's surprising when you encounter it for the first time and easy to forget.

[^1]: For instance, the [Repository permissions for "Contents"](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-contents) page notes this additional permission on the endpoints for updating refs, but not on the other Git endpoints.

**Comment by arunsathiya** [comment]
Bingo, that's it! Thank you, @bluekeyes. 😄
