### ISSUE TITLE
Multiple commits in one patch file are not supported

### ISSUE THREAD

**Issue by katrinafyi** [bluekeyes/patch2pr#88]
In a file with multiple commits (e.g. Github [PR patches](https://patch-diff.githubusercontent.com/raw/NixOS/nixpkgs/pull/285786.patch)), only the first commit is parsed from the `git format-patch` output.

Additional commits can be detected by the "From" headers when the parser is looking for further "diff --git" lines. Fortunately, this is not ambiguous with diff context lines since those always start with +, -, or space.

Edit: I should mention I noticed this via patch2pr. If this is better filed there, feel free to move!

**Comment by bluekeyes** [comment]
After thinking about this more, I decided this is actually a `patch2pr` issue, by analogy to the difference between `git am` (can apply multiple patches as commits) and `git apply` (applies a single patch but does not make a commit.)

My plan is to detect if an input file looks like an `mbox` file (the first non-empty line starts with `From `) and then split the input into messages before passing them to `gitdiff.Parse` individually.

**Comment by katrinafyi** [comment]
Thanks for your help, it works well! I've been using patch2pr with nixpkgs and it's a huge help (~4GB object history). Thanks again :)
